blog/urls.py
from django.urls import path, include, re_path
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from . import views
sitemaps = {
    'post': PostSitemap,
}
app_name = 'blog'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    # path('post/<int:pk>/', views.detail, name='detail'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path("archives/", views.PostArchivesView.as_view(), name="archives"),
    path("categories/", views.CategoryListView.as_view(), name="categories"),
    path("tags/", views.TagListView.as_view(), name="tags"),
    path("about/<int:pk>/", views.AboutDetailView.as_view(), name="about"),
    # path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    path('archives/<int:year>/<int:month>/',views.ArchiveView.as_view(), name='archive'),
    # path('categories/<int:pk>/', views.category, name='category'),
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    # path('tags/<int:pk>/', views.tag, name='tag'),
    path('tags/<int:pk>/', views.TagView.as_view(), name='tag'),
    # path('search/', views.search, name='search'),
    re_path(r'^sitemap\.xml', sitemap, {'sitemaps': sitemaps}),
    re_path(r'^robots\.txt', include('robots.urls')),
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.feeds import AllPostsRssFeed
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('baton/', include('baton.urls')),
    path(r'mdeditor/', include('mdeditor.urls')),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
    path('all/rss/', AllPostsRssFeed(), name='rss'),
    path('search/', include('haystack.urls')), 
]
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from mdeditor.fields import MDTextField
from django.shortcuts import render
import markdown, re
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.utils.html import strip_tags
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.utils.functional import cached_property

# Create your models here.
class Category(models.Model):
  id = models.AutoField(primary_key=True)
  name = models.CharField(max_length=100)

  class Meta:
    verbose_name = '分类'
    verbose_name_plural = verbose_name

  def __str__(self):
    return self.name

class Tag(models.Model):
  id = models.AutoField(primary_key=True)
  name = models.CharField(max_length=100)

  class Meta:
    verbose_name = '标签'
    verbose_name_plural = verbose_name

  def __str__(self):
    return self.name

def generate_rich_content(value):
    md = markdown.Markdown(
        extensions=[
            "markdown.extensions.extra",
            "markdown.extensions.codehilite",
            "markdown.extensions.admonition",
            TocExtension(slugify=slugify),
        ],
    )
    content = md.convert(value)
    n = content.count('<div class="codehilite">', 0, len(content))
    for i in range(n):
        content = re.sub(r'<div class="codehilite">',
                    '<div class="codehilite" id="code{}">'
                    '<button id="ecodecopy" style="position:absolute;right:11%" class="copybtn" '
                    'data-clipboard-action="copy" '
                    'data-clipboard-target="#code{}"> \
                    <i class="iconfont icon-copy"></i><span>复制</span> \
                    </button>'
                    .format(i, i), content, 1)
    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div> ', md.toc, re.S)
    toc = m.group(1) if m is not None else ""
    return {"content": content, "toc": toc}

class About(models.Model):
  id = models.AutoField(primary_key=True)
  name = models.CharField(max_length=100)
  avatar_img = models.ImageField(
      upload_to='images/', blank=True, verbose_name='关于我头像')
  body = MDTextField(verbose_name='正文')

  def __str__(self):
    return self.name

  class Meta:
    verbose_name = '关于'
    verbose_name_plural = verbose_name
    
  def get_absolute_url(self):
    return reverse('blog:about', kwargs={'pk': self.pk})

  def save(self, *args, **kwargs):

    md = markdown.Markdown(extensions=[
        "markdown.extensions.extra",
        "markdown.extensions.codehilite",
        "markdown.extensions.admonition",
        TocExtension(slugify=slugify),
    ])
    super().save(*args, **kwargs)

  @property
  def toc(self):
    return self.rich_content.get("toc", "")

  @property
  def body_html(self):
    return self.rich_content.get("content", "")

  @cached_property
  def rich_content(self):
    return generate_rich_content(self.body)

class Post(models.Model):
  id = models.AutoField(primary_key=True)
  title = models.CharField(max_length=70, verbose_name='标题')
  body = MDTextField(verbose_name='正文')
  created_time = models.DateTimeField(verbose_name='创建时间', default=timezone.now)
  modified_time = models.DateTimeField(verbose_name='修改时间', auto_now=True)
  excerpt = models.CharField(max_length=400, blank=True, verbose_name='摘要信息')
  category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='分类')
  tags = models.ManyToManyField(Tag, blank=True, verbose_name='标签')
  author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')
  views = models.PositiveBigIntegerField(default=0, editable=False)
  index_img = models.ImageField(upload_to='images/', blank=True, verbose_name='文章封面')
  # def save(self, *args, **kwargs):
  #   self.modified_time = timezone.now()
  #   super().save(*args, **kwargs)
  
  def increase_views(self):
    self.views += 1
    self.save(update_fields=['views'])

  class Meta:
    verbose_name = '文章'
    verbose_name_plural = verbose_name
    ordering = ['-created_time', 'title']

  def __str__(self):
    return self.title

  def get_absolute_url(self):
    return reverse('blog:detail', kwargs={'pk': self.pk})

  def save(self, *args, **kwargs):
    self.modified_time = timezone.now()

    md = markdown.Markdown(extensions=[
        "markdown.extensions.extra",
        "markdown.extensions.codehilite",
        "markdown.extensions.admonition",
        TocExtension(slugify=slugify),
    ])
    self.excerpt = strip_tags(md.convert(self.body))[:54]

    super().save(*args, **kwargs)

  @property
  def toc(self):
    return self.rich_content.get("toc", "")

  @property
  def body_html(self):
    return self.rich_content.get("content", "")

  @cached_property
  def rich_content(self):
    return generate_rich_content(self.body)

comments/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(verbose_name='名字', max_length=50)
    email = models.EmailField(verbose_name='邮箱')
    url = models.URLField(verbose_name='网址', blank=True)
    text = models.TextField(verbose_name='内容')
    created_time = models.DateTimeField(
        verbose_name='创建时间', default=timezone.now)
    post = models.ForeignKey(
        'blog.Post', verbose_name='文章', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

blog/views.py
import markdown
import re
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Post, Category, Tag, About
from django.views.generic import ListView, DetailView
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from pure_pagination.mixins import PaginationMixin
from django.contrib import messages
from django.db.models import Q, Count
from braces.views import SetHeadlineMixin

# Create your views here.

# def index(request):
#   post_list = Post.objects.all().order_by('-created_time')
#   return render(request, 'blog/index.html', context={
#     'title': '我的博客首页',
#     'welcome': '欢迎访问我的博客首页',
#     'post_list': post_list,
#   })


class IndexView(PaginationMixin, ListView):
  model = Post
  template_name = 'blog/index.html'
  context_object_name = 'post_list'
  paginate_by = 10

# def detail(request, pk):
#   post = get_object_or_404(Post, pk=pk)

#   post.increase_views()
  
#   md = markdown.Markdown(extensions=[
#     'markdown.extensions.extra',
#     'markdown.extensions.codehilite',
#     'markdown.extensions.toc',
#   ])
#   post.body = md.convert(post.body)

#   m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
#   post.toc = m.group(1) if m is not None else ''

#   return render(request, 'blog/detail.html', context={'post': post})

class PostDetailView(DetailView):
  model = Post
  template_name = 'blog/detail.html'
  context_object_name = 'post'

  def get(self, request, *args, **kwargs):
    response = super(PostDetailView, self).get(request, *args, **kwargs)
    self.object.increase_views()
    return response
  
  # def get_object(self, queryset=None):
  #   post = super().get_object(queryset=None)
  #   md = markdown.Markdown(extensions=[
  #       'markdown.extensions.extra',
  #       'markdown.extensions.codehilite',
  #       TocExtension(slugify=slugify),
  #   ])
    
  #   post.body = md.convert(post.body)
  #   m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
  #   post.toc = m.group(1) if m is not None else ''

  #   return post

# def archive(request, year, month):
#   post_list = Post.objects.filter(created_time__year=year, 
#       created_time__month=month).order_by('created_time')

#   return render(request, 'blog/index.html', context={'post_list': post_list})

class ArchiveView(IndexView):
  def get_queryset(self):
    year = self.kwargs.get('year')
    month = self.kwargs.get('month')
    return super(ArchiveView, self).get_queryset().filter(created_time__year=year, created_time__month=month)
  

class PostArchivesView(SetHeadlineMixin, ListView):
    headline = "归档"
    model = Post
    template_name = "blog/archives.html"

# def category(request, pk):
#     cate = get_object_or_404(Category, pk=pk)
#     post_list = Post.objects.filter(category=cate).order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})

class CategoryView(IndexView):
  def get_queryset(self):
    cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
    return super(CategoryView, self).get_queryset().filter(category=cate)


class CategoryListView(SetHeadlineMixin, ListView):
    model = Category
    headline = "分类"
    template_name = "blog/category.html"
    queryset = Category.objects.all().annotate(num_posts=Count("post"))

# def tag(request, pk):
#     t = get_object_or_404(Tag, pk=pk)
#     post_list = Post.objects.filter(tags=t).order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})
class TagView(IndexView):
  def get_queryset(self):
    t = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
    return super(TagView, self).get_queryset().filter(tags=t)


class TagListView(SetHeadlineMixin, ListView):
    model = Tag
    headline = "标签"
    template_name = "blog/tags.html"


class AboutDetailView(DetailView):
    model = About
    headline = "关于"
    template_name = "blog/about.html"
    context_object_name = 'about'

    def get(self, request, *args, **kwargs):
      response = super(AboutDetailView, self).get(request, *args, **kwargs)
      return response

def search(request):
    q = request.GET.get('q')

    if not q:
        error_msg = "请输入搜索关键词"
        messages.add_message(request, messages.ERROR,
                             error_msg, extra_tags='danger')
        return redirect('blog:index')

    post_list = Post.objects.filter(
        Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'post_list': post_list})

templates/blog/about.html
{% extends 'base.html' %}
{% load static %}
{% block subtitle %}
<div class="banner" id="banner" parallax=true style="background: url('{% static 'blog/img/category.jpg' %}') no-repeat center center;
           background-size: cover;">
  <div class="full-bg-img">
    <div class="mask flex-center" style="background-color: rgba(0, 0, 0, 0.3)">
      <div class="page-header text-center fade-in-up">
        <span class="h2" id="subtitle" title="关于"></span>
      </div>
      <div class="scroll-down-bar">
        <i class="iconfont icon-arrowdown"></i>
      </div>
    </div>
  </div>
</div>
{% endblock subtitle %}
{% block main %}
<div class="about-avatar">
  <img src="{{ about.avatar_img.url }}" class="img-fluid"
    alt="avatar">
</div>
<div class="container">
  <div class="row">
    <div class="col-12 col-md-10 m-auto">
       <p>{{ about.body_html | safe }}</p>
    </div>
  </div>
</div>
{% endblock main %}

templates/blog/archives.html
{% extends 'base.html' %}
{% load static %}
{% block subtitle %}
<div class="banner" id="banner" parallax=true
  style="background: url('{% static 'blog/img/archives.jpg' %}') no-repeat center center;
           background-size: cover;">
  <div class="full-bg-img">
    <div class="mask flex-center" style="background-color: rgba(0, 0, 0, 0.3)">
      <div class="page-header text-center fade-in-up">
        <span class="h2" id="subtitle" title="归档"></span>
      </div>
      <div class="scroll-down-bar">
        <i class="iconfont icon-arrowdown"></i>
      </div>
    </div>
  </div>
</div>
{% endblock subtitle %}
{% block main %}
<div class="list-group">
{% regroup post_list by created_time.year as year_post_group %}
<p class="h4">共计 {{ post_list|length }} 篇文章</p>
<hr>
{% for year in year_post_group %}
<p class="h5">{{ year.grouper }}</p>
{% regroup year.list by created_time.month as month_post_group %}
  {% for month in month_post_group %}
      {% for post in month.list %}
          <a href="{{ post.get_absolute_url }}" class="list-group-item list-group-item-action">
            <span class="archive-post-title">{{ post.title }}</span>
            <time style="float: right;">{{ post.created_time }}</time>
          </a>
      {% endfor %}
  {% endfor %}
{% endfor %}
</div>
{% endblock main %}

templates/blog/category.html
{% extends 'base.html' %}
{% load static %}
{% block subtitle %}
<div class="banner" id="banner" parallax=true style="background: url('{% static 'blog/img/category.jpg' %}') no-repeat center center;
           background-size: cover;">
  <div class="full-bg-img">
    <div class="mask flex-center" style="background-color: rgba(0, 0, 0, 0.3)">
      <div class="page-header text-center fade-in-up">
        <span class="h2" id="subtitle" title="分类"></span>
      </div>
      <div class="scroll-down-bar">
        <i class="iconfont icon-arrowdown"></i>
      </div>
    </div>
  </div>
</div>
{% endblock subtitle %}
{% block main %}
<div class="category-list">
{% for category in category_list %}
  <div class="category row">
    <a class="category-item collapsed list-group-item category-item-action col-10 col-md-11"
      id="heading-{{ category.name }}" role="tab" data-toggle="collapse"
      href="#collapse-{{ category.name }}" aria-expanded="false">
      {{ category.name }}
      <i class="iconfont icon-arrowright"></i>
    </a>
    <a href="{% url 'blog:category' category.pk %}" class="category-count col-2 col-md-1">
      <i class="iconfont icon-articles"></i>
      <span>{{ category.num_posts }}</span>
    </a>
    <div class="category-collapse">
      <div id="collapse-{{ category.name }}" class="collapse in" role="tabpanel"
        aria-labelledby="heading-{{ category.name }}">
        {% for post in post_list %}
        <a href="{{ post.get_absolute_url }}"
          class="list-group-item list-group-item-action">
          <span class="category-post">{{ post.title }}</span>
        </a>
        {% endfor %}
      </div>
    </div>
  </div>
{% endfor %}
</div>
{% endblock main %}

templates/blog/detail.html
{% extends 'base.html' %}
{% load custom_markdown %}
{% load comments_extras %}
{% block subtitle %}
<div class="banner" id="banner" parallax=true style="background: url('{{ post.index_img.url }}') no-repeat center center;
           background-size: cover;">
  <div class="full-bg-img">
    <div class="mask flex-center" style="background-color: rgba(0, 0, 0, 0.3)">
      <div class="page-header text-center fade-in-up">
        <span class="h2" id="subtitle" title="{{ post.title }}"></span>
        <div class="mt-3">
          <span class="post-meta">
            <i class="iconfont icon-date-fill" aria-hidden="true"></i>
            <time datetime="{{ post.created_time }}" pubdate>
              {{ post.created_time }}
            </time>
          </span>
        </div>
        <div class="mt-1">
          <span class="post-meta mr-2">
            <i class="iconfont icon-chart"></i>
            {{ post.comment_set.count }} 评论
          </span>
          <span class="post-meta mr-2">
            <i class="iconfont icon-clock-fill"></i>
            {{ post.views }} 阅读
          </span>
        </div>
      </div>
      <div class="scroll-down-bar">
        <i class="iconfont icon-arrowdown"></i>
      </div>
    </div>
  </div>
</div>
{% endblock subtitle %}
{% block main %}

<article class="post-content mx-auto post post-{{ post.pk }}">
  <header class="entry-header">
    <h1 class="entry-title">{{ post.title }}</h1>
    <div class="entry-meta">
      <span class="post-category"><a href="#"><i class="iconfont icon-tags"></i>
      {{ post.category.name }}</a></span>
      <span class="post-date"><a href="#"><time class="entry-date"
            datetime="{{ post.created_time }}"><i class="iconfont icon-date"></i>
            {{ post.created_time }}</time></a></span>
      <span class="post-author"><a href="#"><i class="iconfont icon-users"></i>
      {{ post.author }}</a></span>
      <span class="comments-link"><a href="#comment-area"><i class="iconfont icon-chart"></i>
                                                  {{ post.comment_set.count }} 评论</a></span>
      <span class="views-count"><a href="#"><i class="iconfont icon-clock-fill"></i>
                                                {{ post.views }} 阅读</a></span>
    </div>
  </header>
  <div class="entry-content clearfix" >
    <p>{{ post.body_html | safe }}</p>
  </div>
  <hr>
  <div>
    <div class="post-metas mb-3">
      <div class="post-meta mr-3">
        <i class="iconfont icon-category"></i>
        <a class="hover-with-bg" href="/categories/DevOps/">{{ post.category.name }}</a>
      </div>
    </div>
    <p class="note note-warning">
      本博客所有文章除特别声明外，均采用 <a target="_blank" href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh"
        rel="nofollow noopener noopener">CC BY-SA 4.0 协议</a> ，转载请注明出处！
    </p>
    {% comment %} <div class="post-prevnext">
      <article class="post-prev col-6">
        <a href="/post/hello-world.html">
          <i class="iconfont icon-arrowleft"></i>
          <span class="hidden-mobile">Hello World</span>
          <span class="visible-mobile">上一篇</span>
        </a>
      </article>
      <article class="post-next col-6">
      </article>
    </div> {% endcomment %}
  </div>
  <section class="comment-area" id="comment-area">
    <hr>
    <h3>发表评论</h3>
    {% show_comment_form post %}
    <div class="comment-list-panel">
      {% show_comments post %}
    </div>
  </section>
</article>
{% endblock main %}
{% block toc %}
{% comment %} <div class="d-none d-lg-block col-lg-2 toc-container" id="toc-ctn">
  <div id="toc" style="visibility: visible;">
    <p class="toc-header"><i class="iconfont icon-list"></i>&nbsp;目录</p>
    <div class="toc-body" id="toc-body">
      <ul>
        {{ post.toc | safe }}
      </ul>
    </div>
  </div>
</div> {% endcomment %}
<div class="d-none d-lg-block col-lg-2 toc-container">
  <div id="toc" style="visibility: visible;">
    <div class="toc-header"><i class="iconfont icon-list"></i>&nbsp;目录</div>
    <div style="max-height: calc(100vh - 120px); overflow: hidden; overflow-y: auto;">
        <nav class="nav flex-column" id="post-toc"></nav>
    </div>
  </div>
</div>
{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% block subtitle %}
<div class="banner" id="banner" parallax=true style="background: url('{% static 'blog/img/banner.jpg' %}') no-repeat center center;
           background-size: cover;">
    <div class="full-bg-img">
        <div class="mask flex-center" style="background-color: rgba(0, 0, 0, 0.3)">
            <div class="page-header text-center fade-in-up">
                <span class="h2" id="subtitle" title="不断学习是成功的最基本要素。"></span>
            </div>
            <div class="scroll-down-bar">
                <i class="iconfont icon-arrowdown"></i>
            </div>
        </div>
    </div>
</div>
{% endblock subtitle %}
{% block main %}
{% for post in post_list %}
    <div class="row mx-auto index-card">
        <div class="col-12 col-md-4 m-auto index-img">
            <a href="{{ post.get_absolute_url }}"
                target="_self">
                <img src="{{ post.index_img.url }}"
                    srcset="{% static 'blog/img/loading.gif' %}" 
                    lazyload alt="">
            </a>
        </div>
        <article class="col-12 col-md-8 mx-auto index-info">
            <h1 class="index-header">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h1>
            <p class="index-excerpt">
                <a href="{{ post.get_absolute_url }}">{{ post.excerpt }}...</a>
            </p>
            <div class="index-btm post-metas">
                <div class="post-meta mr-3">
                    <i class="iconfont icon-date"></i>
                    <time datetime="{{ post.created_time }}" pubdate>
                        {{ post.created_time }}
                    </time>
                </div>
                <div class="post-meta mr-3">
                    <i class="iconfont icon-category"></i>
                    <a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a>
                </div>
                <div class="post-meta">
                    <i class="iconfont icon-tags"></i>
                      {% for tag in  post.tags.all %}
                        <a href="{% url 'blog:tag' tag.pk %}">{{ tag }}</a>
                      {% endfor %}
                </div>
            </div>
        </article>
    </div>
{% empty %}
<div class="no-post">暂时还没有发布的文章！</div>
{% endfor %}
<nav aria-label="navigation">
    {% if is_paginated %}
    {{ page_obj.render }}
    {% endif %}
</nav>
{% endblock main %}

{% block toc %}
{% endblock toc %}

templates/blog/tags.html
{% extends 'base.html' %}
{% load static %}
{% block subtitle %}
<div class="banner" id="banner" parallax=true style="background: url('{% static 'blog/img/tags.jpg' %}') no-repeat center center;
           background-size: cover;">
  <div class="full-bg-img">
    <div class="mask flex-center" style="background-color: rgba(0, 0, 0, 0.3)">
      <div class="page-header text-center fade-in-up">
        <span class="h2" id="subtitle" title="标签云"></span>
      </div>
      <div class="scroll-down-bar">
        <i class="iconfont icon-arrowdown"></i>
      </div>
    </div>
  </div>
</div>
{% endblock subtitle %}
{% block main %}
<div class="text-center tagcloud">
{% for tag in tag_list %}
  <a href="{% url 'blog:tag' tag.pk %}" style="font-size: 15px; color: #bbe">{{ tag.name }}</a>
{% endfor %}
</div>
{% endblock main %}